"""
学习使用PIL库读取图片并转换为numpy数组
学习使用transforms库将图片转换为tensor
思考一下numpy和tensor的区别
可以用调试器查看变量的类型和值
"""

In [1]:
#导入库
from PIL import Image
from torchvision import transforms
import numpy as np

In [2]:
#打开并读取图片
img = Image.open('./test.png')
print(img.size)
print(img.format)
print(img)

(2560, 1528)
PNG
<PIL.PngImagePlugin.PngImageFile image mode=RGBA size=2560x1528 at 0x23D732CB3B0>


In [3]:
#转换为numpy数组
img1 = np.array(img)
print(img1.shape)
print(img1.dtype)
print(img1[0])

(1528, 2560, 4)
uint8
[[ 18  42  69 255]
 [ 18  42  69 255]
 [ 18  42  69 255]
 ...
 [ 18  42  69 255]
 [ 18  42  69 255]
 [ 18  42  69 255]]


In [4]:
#转换为tensor
img2 = transforms.ToTensor()(img)
print(img2.shape)
print(img2.dtype)
print(img2)

torch.Size([4, 1528, 2560])
torch.float32
tensor([[[0.0706, 0.0706, 0.0706,  ..., 0.0706, 0.0706, 0.0706],
         [0.0706, 0.0706, 0.0706,  ..., 0.0706, 0.0706, 0.0706],
         [0.0706, 0.0706, 0.0706,  ..., 0.0706, 0.0706, 0.0706],
         ...,
         [0.1333, 0.1333, 0.1333,  ..., 0.1333, 0.1333, 0.1333],
         [0.1333, 0.1333, 0.1333,  ..., 0.1333, 0.1333, 0.1333],
         [0.1333, 0.1333, 0.1333,  ..., 0.1333, 0.1333, 0.1333]],

        [[0.1647, 0.1647, 0.1647,  ..., 0.1647, 0.1647, 0.1647],
         [0.1647, 0.1647, 0.1647,  ..., 0.1647, 0.1647, 0.1647],
         [0.1647, 0.1647, 0.1647,  ..., 0.1647, 0.1647, 0.1647],
         ...,
         [0.2941, 0.2941, 0.2941,  ..., 0.2941, 0.2941, 0.2941],
         [0.2941, 0.2941, 0.2941,  ..., 0.2941, 0.2941, 0.2941],
         [0.2941, 0.2941, 0.2941,  ..., 0.2941, 0.2941, 0.2941]],

        [[0.2706, 0.2706, 0.2706,  ..., 0.2706, 0.2706, 0.2706],
         [0.2706, 0.2706, 0.2706,  ..., 0.2706, 0.2706, 0.2706],
         [0.2706